name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: cheat-engine/cheat-engine
        ref: '7.5'

    - uses: gcarreno/setup-lazarus@v3.2.15
      with:
        lazarus-version: "2.2.2"

#     - run: |
#         if (-not (Test-Path lazarus-2.2.0-fpc-3.2.2-win64.exe)) {
#             curl.exe -LO https://udomain.dl.sourceforge.net/project/lazarus/Lazarus%20Windows%2064%20bits/Lazarus%202.2.0/lazarus-2.2.0-fpc-3.2.2-win64.exe
#         }
#         ./lazarus-2.2.0-fpc-3.2.2-win64.exe /verysilent

    - run: lazbuild -B "Cheat Engine/cheatengine.lpi" --cpu=x86_64 --build-mode="Release 64-Bit O4 AVX2"

#     - run: ls -r '*.lpi' | % { lazbuild -B $_ --cpu=x86_64 --build-mode="Release 64-Bit O4 AVX2" }
    
    - run: 7z a CE.7z ".\Cheat Engine\bin\*"

    - uses: actions/upload-artifact@master
      with:
        path: CE.7z
        name: CE.7z
